language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cordojo' ]; then cd .. && eval "mv $currentfolder generator-cordojo" && cd generator-cordojo; fi

